name: simple OS Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build simple OS using Docker Compose on Ubuntu.
      run: docker build . --file Dockerfile --tag  mindtrix/simple-os:$(date +%s)
